/**
 * @file NodeConditionsPanel.h
 * @brief UI panel for multi-condition selection on a NodeBranch (Phase 24.2).
 * @author Olympe Engine
 * @date 2026-03-17
 *
 * @details
 * NodeConditionsPanel renders the condition-assignment UI embedded in (or
 * docked beside) a NodeBranch properties panel.  It lets the user:
 *   - Select one or more ConditionPresets from the global registry.
 *   - Set the logical operator (And / Or) between consecutive conditions.
 *   - View the dynamic data pins that were generated by DynamicDataPinManager.
 *   - Remove individual conditions from the node.
 *
 * The panel owns a copy of the node's `std::vector<NodeConditionRef>` and
 * exposes change-callbacks so the host can write back to the node definition.
 *
 * Layout:
 * @code
 * ╔══════════════════════════════════════════════════════════╗
 * ║  Conditions                                              ║
 * ├──────────────────────────────────────────────────────────┤
 * ║ [Start] [mHealth] <= [2]  (Condition #1)           [X]  ║
 * ║ [And  ] [mSpeed] > [0]    (Fast)                   [X]  ║
 * ║ [+ Add Condition]                                        ║
 * ├──────────────────────────────────────────────────────────┤
 * ║  Dynamic Pins                                            ║
 * ║  (none)                                                  ║
 * ╚══════════════════════════════════════════════════════════╝
 * @endcode
 *
 * C++14 compliant — no std::optional, structured bindings, std::filesystem.
 */

#pragma once

#include <string>
#include <vector>
#include <functional>

#include "../ConditionPreset/ConditionPreset.h"
#include "../ConditionPreset/ConditionPresetRegistry.h"
#include "../ConditionPreset/NodeConditionRef.h"
#include "../ConditionPreset/DynamicDataPin.h"

namespace Olympe {

/**
 * @class NodeConditionsPanel
 * @brief ImGui sub-panel for managing the condition list of a single NodeBranch.
 *
 * @details
 * The panel does NOT own the registry — it holds a reference.
 * The caller is responsible for persisting changes from GetConditionRefs()
 * back to the node definition.
 *
 * Dependency injection:
 *   NodeConditionsPanel panel(registry);
 *   panel.SetConditionRefs(node.conditions);
 *   panel.SetDynamicPins(node.dynamicPins);   // optional read-only display
 *   panel.Render();
 *   if (panel.IsDirty()) {
 *       node.conditions  = panel.GetConditionRefs();
 *       panel.ClearDirty();
 *   }
 */
class NodeConditionsPanel {
public:

    /**
     * @brief Constructs the panel bound to a global preset registry.
     * @param registry  Global ConditionPresetRegistry (must outlive this panel).
     */
    explicit NodeConditionsPanel(ConditionPresetRegistry& registry);

    ~NodeConditionsPanel() = default;

    // Non-copyable
    NodeConditionsPanel(const NodeConditionsPanel&) = delete;
    NodeConditionsPanel& operator=(const NodeConditionsPanel&) = delete;

    // -----------------------------------------------------------------------
    // State accessors
    // -----------------------------------------------------------------------

    /**
     * @brief Replaces the panel's internal condition list.
     *
     * Typically called when a new node is selected in the editor.
     *
     * @param refs  Condition references from node.conditions.
     */
    void SetConditionRefs(const std::vector<NodeConditionRef>& refs);

    /**
     * @brief Returns the current (possibly modified) condition list.
     */
    const std::vector<NodeConditionRef>& GetConditionRefs() const;

    /**
     * @brief Provides the read-only list of dynamic pins for display.
     *
     * The panel shows these pins in a read-only section.  Ownership stays
     * with the DynamicDataPinManager; the panel only renders them.
     *
     * @param pins  Current dynamic pins associated with this node.
     */
    void SetDynamicPins(const std::vector<DynamicDataPin>& pins);

    /**
     * @brief Returns true if the condition list has been modified since the
     *        last call to ClearDirty().
     */
    bool IsDirty() const { return m_dirty; }

    /**
     * @brief Resets the dirty flag.
     */
    void ClearDirty() { m_dirty = false; }

    // -----------------------------------------------------------------------
    // Rendering (ImGui — guarded by OLYMPE_HEADLESS in tests)
    // -----------------------------------------------------------------------

    /**
     * @brief Renders the condition list and dynamic-pin display using ImGui.
     *
     * Must be called once per frame inside an ImGui window context.
     * Internally wrapped in `#ifndef OLYMPE_HEADLESS` so tests can call
     * the logic methods without linking ImGui.
     */
    void Render();

    // -----------------------------------------------------------------------
    // Callbacks
    // -----------------------------------------------------------------------

    /** Fired when a preset is selected or changed.  Arg: preset ID. */
    std::function<void(const std::string&)> OnPresetChanged;

    /**
     * @brief Should be called by the host when a preset is deleted from the
     *        registry.  Removes any NodeConditionRef pointing to that preset.
     *
     * @param deletedPresetID  UUID of the preset that was removed.
     */
    void OnPresetDeleted(const std::string& deletedPresetID);

    // -----------------------------------------------------------------------
    // Condition management (also testable without ImGui)
    // -----------------------------------------------------------------------

    /**
     * @brief Appends a new condition reference with the given preset.
     *
     * The logicalOp is automatically set to LogicalOp::And (except for
     * the first entry, which receives LogicalOp::Start).
     *
     * @param presetID  UUID of the ConditionPreset to reference.
     */
    void AddCondition(const std::string& presetID);

    /**
     * @brief Removes the condition at the given index.
     * @param index  Zero-based index in the condition list.
     */
    void RemoveCondition(size_t index);

    /**
     * @brief Changes the logical operator for the condition at the given index.
     *
     * Index 0 is always forced to LogicalOp::Start regardless of the value
     * passed in.
     *
     * @param index  Zero-based index.
     * @param op     New LogicalOp (And or Or; Start is ignored for index > 0).
     */
    void SetLogicalOp(size_t index, LogicalOp op);

    /**
     * @brief Returns the number of conditions currently in the list.
     */
    size_t GetConditionCount() const;

    // -----------------------------------------------------------------------
    // Validation
    // -----------------------------------------------------------------------

    /**
     * @brief Returns true when every condition ref points to an existing preset.
     */
    bool IsValid() const;

    /**
     * @brief Returns a list of error strings describing validation failures.
     *
     * Empty if IsValid() returns true.
     */
    std::vector<std::string> Validate() const;

    // -----------------------------------------------------------------------
    // Search helper (used by the dropdown)
    // -----------------------------------------------------------------------

    /**
     * @brief Sets the search/filter string used by the "Add Condition" dropdown.
     * @param filter  Substring filter (empty = show all).
     */
    void SetDropdownFilter(const std::string& filter);

    /**
     * @brief Returns the current dropdown filter.
     */
    const std::string& GetDropdownFilter() const { return m_dropdownFilter; }

    /**
     * @brief Returns presets matching the current dropdown filter.
     *
     * Delegates to ConditionPresetRegistry::FindPresetsByName when the filter
     * is non-empty; returns all presets otherwise.
     */
    std::vector<ConditionPreset> GetFilteredPresetsForDropdown() const;

private:

    // -----------------------------------------------------------------------
    // ImGui rendering helpers
    // -----------------------------------------------------------------------

    void RenderConditionRow(size_t index, const NodeConditionRef& ref);
    void RenderAddConditionDropdown();
    void RenderDynamicPinsSection();

    // -----------------------------------------------------------------------
    // Internal helpers
    // -----------------------------------------------------------------------

    /** Fixes up the first condition's logicalOp to always be Start. */
    void NormalizeLogicalOps();

    // -----------------------------------------------------------------------
    // State
    // -----------------------------------------------------------------------

    ConditionPresetRegistry&       m_registry;     ///< Shared global registry
    std::vector<NodeConditionRef>  m_conditionRefs;///< Current node's conditions
    std::vector<DynamicDataPin>    m_dynamicPins;  ///< Read-only dynamic pins for display
    bool                           m_dirty = false;///< Modification flag

    std::string  m_dropdownFilter;    ///< Filter text for "Add Condition" dropdown
    bool         m_dropdownOpen = false; ///< Whether the add-dropdown is shown
};

} // namespace Olympe
